version: '3'

services:
  app:
    build: app
    container_name: app
    # ports:
    #   - "8000:8000"
    networks:
      - app_network

  nginx:
    build: nginx
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge